### ISSUE TITLE
List tests available

### ISSUE THREAD

**Issue by TrevorSayre** [pvinis/colortools#1]
Currently I have to visit the README in order to know what tests are available from colortest. It would be handy to have the command `colortest` print out the available tests with a text description.

**Comment by pvinis** [comment]
should be easy enough to hardcode them and print them. good idea. I usually just tab-complete.

**Comment by TrevorSayre** [comment]
I agree, tab complete does help, but it doesn't provide a description or reminder that the commands are `ct-` prefixed when I just look in my `brew list` and see a `colortools` installation that doesn't have a same-name binary.

**Comment by pvinis** [comment]
i added a main script that lists all the rest with a short description, plus changed the names from `ct-*` to `colortools-*`.

version 1.0 is out with that, and its also updated on `pvinis/pvinis/colortools` from homebrew.

thanks for the idea.
